Feat/keyp 398 build stub plugin 2.0
eclipse/keyple-java-plugin-stub pull request #1
Opened 2021-04-30 10:39 UTC by odelcroi

Main evolutions : 
- Stub plugin can be initialized with already plugged readers (and inserted smart cards)
- Ease the creation of stub smart card with a proper builder
- Globally simplify the interfaces

2021-05-06 14:58 UTC, andrei-cristea requested changes
De manière générale, il manque les @since sur tous les éléments package-private. Il n'y a que pour les éléments privés pour lesquels cette annotation est inutile.

2021-05-06 14:58 UTC, andrei-cristea commented on PUBLISHERS.yml
> +url: https://github.com/eclipse/keyple-java-plugin-pcsc
il faut adapter ce fichier

2021-05-06 14:58 UTC, andrei-cristea commented on src/main/java/org/eclipse/keyple/plugin/stub/StubPlugin.java
> +  String PLUGIN_NAME = "StubPlugin";
Pas de constante dans les interfaces.

2021-05-06 14:58 UTC, andrei-cristea commented on src/main/java/org/eclipse/keyple/plugin/stub/StubPluginAdapter.java
> +    this.stubReaders = new HashMap<String, StubReaderAdapter>();
Si la map peut être accédée par plusieurs threads, je te suggère new ConcurrentHashMap

2021-05-06 14:58 UTC, andrei-cristea commented on src/main/java/org/eclipse/keyple/plugin/stub/StubPluginAdapter.java
> +    return stubReaders.keySet();
Ne pas oublier que le keySet() retourne un pointeur les clés de la map. Donc si l'utilisateur remove un élément du set, il sera supprimé de la map source.
Si cela est un problème, alors faire un new HashSet(....keySet())

2021-05-06 14:58 UTC, andrei-cristea commented on src/main/java/org/eclipse/keyple/plugin/stub/StubReaderAdapter.java
> +    implements StubReader, ObservableReaderSpi, WaitForCardInsertionNonBlockingSpi {
Si le reader est observable, il faut impérativement qu'il implémente une interface pour chacun des états (insertion, processing, removal).

2021-05-06 14:58 UTC, andrei-cristea commented on src/main/java/org/eclipse/keyple/plugin/stub/StubSmartCard.java
> +      hexCommands = new HashMap<String, String>();
HashMap ou ConcurrentHashMap ?

2021-05-06 15:18 UTC, jeanpierrefortune approved these changes

2021-05-07 09:58 UTC, odelcroi commented on src/main/java/org/eclipse/keyple/plugin/stub/StubPluginAdapter.java
> +    this.stubReaders = new HashMap<String, StubReaderAdapter>();
good point

2021-05-07 09:59 UTC, odelcroi commented on src/main/java/org/eclipse/keyple/plugin/stub/StubSmartCard.java
> +      hexCommands = new HashMap<String, String>();
Hashmap is enough here

2021-05-07 09:59 UTC, odelcroi commented on PUBLISHERS.yml
> +url: https://github.com/eclipse/keyple-java-plugin-pcsc
good point

2021-05-07 13:31 UTC, odelcroi commented on src/main/java/org/eclipse/keyple/plugin/stub/StubReaderAdapter.java
> +    implements StubReader, ObservableReaderSpi, WaitForCardInsertionNonBlockingSpi {
good point

2021-05-07 15:57 UTC, andrei-cristea approved these changes

2021-05-10 08:05 UTC, merged